---
Name: CommerceGroupedProduct
After: 'framework/*'
---
CatalogueAdmin:
  extensions:
    - GroupedProduct_CatalogueAdmin
CatalogueProduct:
  extensions:
    - GroupedProduct_CatalogueProduct
Product_Controller:
  extensions:
    - GroupedProduct_ProductController
